src/main/java/com/_up/megastore/controllers/implementations/ProductController.java, src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java, src/main/java/com/_up/megastore/data/repositories/IProductRepository.java, src/main/java/com/_up/megastore/exception/ExceptionControllerAdvice.java, src/main/java/com/_up/megastore/services/implementations/ProductService.java, src/main/java/com/_up/megastore/services/interfaces/IProductService.java
Se agregó el endpoint para restaurar los productos que fueron previamente eliminados. Se utilizó un Patch puesto que se actualiza únicamente la flag 'deleted' a false de la entidad. En cuanto a la validación, se utilizaron Query Methods para manejar todas las posibilidades
=> feat: restore products

pom.xml, src/main/java/com/_up/megastore/MegastoreApplication.java, src/main/java/com/_up/megastore/config/CorsConfig.java, src/main/java/com/_up/megastore/controllers/implementations/ProductController.java, src/main/java/com/_up/megastore/controllers/implementations/UserController.java, src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java, src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java, src/main/java/com/_up/megastore/controllers/requests/ActivateUserRequest.java, src/main/java/com/_up/megastore/data/model/User.java, src/main/java/com/_up/megastore/data/repositories/IUserRepository.java, src/main/java/com/_up/megastore/exception/custom_exceptions/EmailSendingException.java, src/main/java/com/_up/megastore/services/implementations/EmailService.java, src/main/java/com/_up/megastore/services/implementations/ProductService.java, src/main/java/com/_up/megastore/services/implementations/UserService.java, src/main/java/com/_up/megastore/services/interfaces/IEmailService.java, src/main/java/com/_up/megastore/services/interfaces/IProductService.java, src/main/java/com/_up/megastore/services/interfaces/IUserService.java, src/main/resources/META-INF/additional-spring-configuration-metadata.json, src/main/resources/application-development.yaml, src/main/resources/application.yaml
Se implementó el envío de un mail de confirmación para activar la cuenta de un usuario.
Decidí implementar el UserController con el endpoint `/api/v1/users/{userId}/activate` porque me hacia mas sentido relacionarlo con la entidad usuario.
Ahora bien, el flujo es el siguiente:
- Se solicita el endpoint para crear un usuario.
- Se envía la confirmación del mail y se crea al usuario
- Si el envío falla, no se crea el usuario (debatible)
- Cuando el usuario ingresa al enlace que se le envió al mail, se redirige a una pagina del front que tiene un botón para realizar una petición de tipo POST al endpoint del UserController mencionado anteriormente.
- Si todo sale bien, como se ve en el gif, se redirecciona al usuario para logearse.
- Si sale mal, se muestra una alerta con el error definido en …
=> feat: send confirmation email

src/main/java/com/_up/megastore/controllers/implementations/ProductController.java, src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java, src/main/java/com/_up/megastore/controllers/responses/ProductResponse.java, src/main/java/com/_up/megastore/data/model/Product.java, src/main/java/com/_up/megastore/data/model/ProductImage.java, src/main/java/com/_up/megastore/data/repositories/IProductImageRepository.java, src/main/java/com/_up/megastore/services/implementations/ProductImageService.java, src/main/java/com/_up/megastore/services/implementations/ProductService.java, src/main/java/com/_up/megastore/services/interfaces/IProductImageService.java, src/main/java/com/_up/megastore/services/interfaces/IProductService.java, src/main/java/com/_up/megastore/services/mappers/ProductMapper.java
Se agregó la funcionalidad para registrar más de una imagen representativa de un producto, con el objetivo de permitir a los clientes visualizar en mayor detalle los productos.
Se modificaron dos operaciones:
- El **registrar producto**, que recibirá como parámetro **obligatorio** un array de MultipartFiles (si sólo se dispone de una imagen el array contendrá un elemento --no es obligatorio subir más de una imagen).
- El **actualizar producto**, que recibirá como parámetro **no obligatorio** un array de MultipartFiles. En caso de que este array exista, las nuevas imágenes se agregarán al producto y se sumarán a las anteriores.
Queda como deuda técnica la funcionalidad para eliminar las imágenes de un producto.
=> ref: multiple images

src/main/java/com/_up/megastore/services/implementations/CategoryService.java
Se solucionó el bug de la actualización de super categorías. Anteriormente, cuando se intentaba actualizar la super categoría de una categoría que NO la tenía (esto es, su atributo era null), el método devolvía un NullPointerException.
Ahora se agregó una condición para que, si la ID de la supercategoría en el update request existe, se busque y se reemplace. En caso de no existir, la super categoría será reemplazada por un null.
=> fix: update supercategory

src/main/java/com/_up/megastore/controllers/requests/CreateProductRequest.java, src/main/java/com/_up/megastore/controllers/requests/UpdateProductRequest.java, src/main/java/com/_up/megastore/data/pipes/ProductName.java, src/main/java/com/_up/megastore/data/pipes/ProductNameValidator.java, src/main/java/com/_up/megastore/data/repositories/IProductRepository.java, src/main/java/com/_up/megastore/services/implementations/ProductImageService.java, src/main/java/com/_up/megastore/services/implementations/ProductService.java
Se agregó un método extra dentro del product service para validar que el producto que estemos por registrar (o actualizar) no tenga el nombre de otro producto ya existente. 
Por defecto, la implementación de los query methods de JPA (existsBy, findBy) respecto a los strings **no es case sensitive**, esto es, si quiero registrar un producto con el nombre "Camiseta Adidas" pero en la base de datos ya existe un producto con nombre "CAMISETA ADIDAS" se lanzará la excepción. A esto lo dejé así de forma intencional teniendo en cuenta los ejemplos que mostró el profe en clase.
Una interrogante que me surgió sobre esto es **cómo manejar la restauración de productos**. Si nosotros borramos un producto (lógicamente) y luego queremos registrar un nuevo producto que tenga el mismo nombre que el …
=> feat: product name validation

src/main/java/com/_up/megastore/MegastoreApplication.java, src/main/java/com/_up/megastore/services/interfaces/IEmailService.java
Teniendo en cuenta que en nuestra implementación **no necesitamos esperar al envío de los correos**, es posible realizar esto de manera [asíncrona](https://medium.com/@dvikash1001/springboot-async-the-magic-and-the-gotchas-17f9471c6fe4) para mejorar el rendimiento y agilizar las peticiones. Por ello, se implementó el uso de las anotaciones para hacer asíncrono el envío de correos a través del Java Mail Sender.
Long story short, en Spring Boot, cuando se llama a un método asíncrono, este se ejecuta en un thread distinto del que se llamó, permitiendo a este último continuar con la siguiente tarea. Teniendo esto en cuenta, podemos devolver, por ejemplo, el 200 OK al usuario que se acaba de registrar sin esperar a que se envíe el correo electrónico, haciendo mucho más rápida la petición. Lo …
=> ref: async email sending

src/main/java/com/_up/megastore/controllers/responses/CategoryResponse.java, src/main/java/com/_up/megastore/services/mappers/CategoryMapper.java
Se retorna ademas del nombre la ID de la super categoría en caso de que exista. Ya que, en el lado del cliente, este dato es de vital importancia al querer actualizar una categoría.
=> ref: return super category id

src/main/java/com/_up/megastore/controllers/requests/CreateCategoryRequest.java, src/main/java/com/_up/megastore/controllers/requests/CreateProductRequest.java, src/main/java/com/_up/megastore/controllers/requests/CreateSizeRequest.java, src/main/java/com/_up/megastore/controllers/requests/UpdateCategoryRequest.java, src/main/java/com/_up/megastore/controllers/requests/UpdateProductRequest.java, src/main/java/com/_up/megastore/controllers/requests/UpdateSizeRequest.java
Teniendo en cuenta lo mencionado en la [PR de administración de tamaños del front](https://github.com/7-Seven-Up/megastore-frontend/pull/15), se agregaron las validaciones de los mínimos para los tamaños, productos y categorías. 
Para no complicar las cosas, usé el siguiente lineamiento de forma global:
- 3 caracteres como mínimo para los **nombres**
- 5 caracteres como mínimo para la **descripción**
=> feat: min validations

src/main/java/com/_up/megastore/controllers/implementations/UserController.java, src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java, src/main/java/com/_up/megastore/controllers/requests/SendEmailRequest.java, src/main/java/com/_up/megastore/data/model/User.java, src/main/java/com/_up/megastore/data/repositories/ITokenRepository.java, src/main/java/com/_up/megastore/security/utils/Endpoints.java, src/main/java/com/_up/megastore/services/implementations/TokenService.java, src/main/java/com/_up/megastore/services/implementations/UserService.java, src/main/java/com/_up/megastore/services/interfaces/ITokenService.java, src/main/java/com/_up/megastore/services/interfaces/IUserService.java
Se agregó un endpoint para permitirles a los usuarios solicitar un nuevo token de activación. Con la generación de este nuevo token, los tokens anteriores se expirarán automáticamente para mantener el orden y la seguridad.
Algunas consideraciones:
- Se utilizó la misma plantilla de correo de activación utilizada en #2
- Para expirar los tokens automáticamente se utilizó un query method
- Se modificó la request de correo utilizada en #4 para aplicarla globalmente también a esta funcionalidad
=> feat: resend activation email

src/main/java/com/_up/megastore/controllers/implementations/UserController.java, src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java, src/main/java/com/_up/megastore/controllers/requests/SendNewActivationTokenRequest.java, src/main/java/com/_up/megastore/security/utils/Endpoints.java, src/main/java/com/_up/megastore/services/implementations/UserService.java, src/main/java/com/_up/megastore/services/interfaces/IUserService.java, src/main/java/com/_up/megastore/utils/EmailBuilder.java
Se agregó la funcionalidad para enviar un nuevo token de activación en caso de que a un usuario se le haya expirado su token. Como en un futuro vamos a refactorizar la funcionalidad para evitar mostrar las ID de los usuarios, lo único que recibiremos es el token (ya expirado) a través del cual buscaremos a un usuario y le enviaremos un nuevo token con un correo personalizado.
Me tomé también la libertad de refactorizar la **construcción de correos**. Separé los métodos de generación de bodies a una nueva clase personalizada: un _EmailBuilder_. Con esto dejamos un poco más limpio al UserService
En un futuro habría que agregar un nuevo endpoint para recibir también las solicitudes de nuevos tokens de activación a través del correo electrónico. Esta implementación en particular funciona para …
=> feat: resend expired activation

src/main/java/com/_up/megastore/data/model/Product.java, src/main/java/com/_up/megastore/data/repositories/IProductRepository.java, src/main/java/com/_up/megastore/services/implementations/ProductService.java
Se agregó la funcionalidad para evitar borrar productos que contengan variantes (siempre y cuando estas no estén ya borradas). Se utilizó un query method justamente para tener en cuenta este borrado lógico.
=> fix: delete product with variants

src/main/java/com/_up/megastore/controllers/requests/CreateCategoryRequest.java, src/main/java/com/_up/megastore/controllers/requests/UpdateCategoryRequest.java
Se realizaron cambios en tanto en el CreateCategoryRequest como UpdateCategoryRequest, para que no valide  el tamaño minimo de la descripcion de la categoría.
=> fix: minimum-length-category-description

src/main/java/com/_up/megastore/config/AuthConfig.java, src/main/java/com/_up/megastore/exception/ExceptionControllerAdvice.java, src/main/java/com/_up/megastore/exception/ExceptionMessages.java
Esta PR está relacionada a la issue #91. Para solucionar este problema, agregué una configuración extra en el Jackson Mapper y cacheé las excepciones correspondientes.
Para cada error ocurrido en el serializador, se lanza un HttpMessageNoReadableException. Como esta excepción es sumamente general y no tiene sentido manejarla de forma global, los mensajes de respuesta se enviarán según la excepción que la haya **causado**. Para ello, decidí usar un switch-case puesto que en un futuro podríamos manejar más excepciones causantes.
El enfoque mencionado en la parte de arriba podría utilizarse también para manejar el error que ocurre cuando subimos a Cloudinary una imagen mayor al límite.
=> fix: float mapping

src/main/java/com/_up/megastore/controllers/implementations/ProductController.java, src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java, src/main/java/com/_up/megastore/data/repositories/IProductRepository.java, src/main/java/com/_up/megastore/services/implementations/ProductService.java, src/main/java/com/_up/megastore/services/interfaces/IProductService.java, src/test/java/com/_up/megastore/integrations/base/BaseIntegrationTest.java, src/test/java/com/_up/megastore/integrations/implementations/ProductControllerTest.java, src/test/resources/scripts/products/get_variants.sql
Se realizaron los siguientes cambios para agilizar la muestra de variables de los productos:
1. El endpoint /api/v1/products ahora devuelve únicamente productos que NO tengan super-producto, esto es, no devuelve variantes
2. Se agregó un nuevo endpoint /api/v1/products/{id}/variants para devolver una lista con las variantes de un producto
Se realizaron los tests de integración correspondientes para estos métodos. Para ello, se creó un archivo .sql para cargar unos registros previos a la base de datos de testing.
Se crearon dos productos: un producto base (sin variantes) y una variante del producto base. Se testeó, entonces, que al pegarle a /api/v1/products sólo se devuelva el producto base y que al pegarle a /api/v1/products/{idDelBase}/variants sólo se devuelva la variante.
**PD**: el …
=> ref: get products

src/main/java/com/_up/megastore/controllers/implementations/OrderController.java, src/main/java/com/_up/megastore/controllers/interfaces/IOrderController.java, src/main/java/com/_up/megastore/data/enums/State.java, src/main/java/com/_up/megastore/data/model/OrderDetail.java, src/main/java/com/_up/megastore/data/repositories/IOrderRepository.java, src/main/java/com/_up/megastore/services/implementations/OrderDetailService.java, src/main/java/com/_up/megastore/services/implementations/OrderService.java, src/main/java/com/_up/megastore/services/interfaces/IOrderService.java, src/main/java/com/_up/megastore/services/mappers/OrderDetailMapper.java, src/main/java/com/_up/megastore/services/mappers/OrderMapper.java, src/main/java/com/_up/megastore/utils/EmailBuilder.java, src/test/java/com/_up/megastore/integrations/implementations/OrderControllerTest.java, src/test/resources/scripts/orders/finish_order.sql
Se implementó la funcionalidad para cambiar una orden de estado 'en progreso' a 'finalizada'. Acorde a nuestra seguridad, el endpoint está autorizado únicamente para **administradores**. Además, se realizó un poco de refactoreo en el OrderService y en el OrderMapper para hacer menos rígida la OrderResponse. 
Una vez las órdenes son actualizadas, se le envía un correo electrónico al cliente avisándole de este cambio de estado y pasándole también el link para que pueda consultar su pedido (si la URL del front no es correcta, esto se cambia).
Para los tests, se hicieron, nuevamente, dos test de integración acorde a la documentación en Notion sobre los test de transición de estados. Se testea que una orden en estado IN_PROGRESS pase a FINISHED, y posteriormente se testea que una orden que no …
=> feat: finish order

src/main/java/com/_up/megastore/controllers/implementations/OrderController.java, src/main/java/com/_up/megastore/controllers/interfaces/IOrderController.java, src/main/java/com/_up/megastore/data/enums/State.java, src/main/java/com/_up/megastore/security/filter/JWTAuthenticationFilter.java, src/main/java/com/_up/megastore/services/implementations/OrderService.java, src/main/java/com/_up/megastore/services/interfaces/IOrderService.java, src/main/java/com/_up/megastore/utils/EmailBuilder.java, src/test/java/com/_up/megastore/integrations/implementations/OrderControllerTest.java, src/test/java/com/_up/megastore/services/implementations/OrderServiceTest.java, src/test/resources/scripts/orders/deliver_order.sql, src/test/resources/scripts/orders/mark_order_in_delivery.sql
Se implementó la funcionalidad para **marcar un pedido como 'en entrega'** y para **entregarlo**. Decidí unir estas funcionalidades para no hacer tantas MR. Además de ello, se refactorizó la construcción de correos electrónicos para enviar los estados de las órdenes, y se agregó también el funcionamiento para enviar correos que confirmen la creación de los pedidos.
Esto es lo más importante. Al igual que en #99, se hicieron dos tests unitarios para cada mini-feature (marcar como en entrega y entregar), uno con un escenario exitoso y otro con un escenario inválido.
Además de ello, también se implementaron los **tests unitarios de transición de estados**, documentados en Notion. Estos tests unitarios aplican al OrderService, particularmente a cada uno de los métodos para pasar de un estado …
=> feat: deliver order

src/main/java/com/_up/megastore/config/AuthConfig.java, src/main/java/com/_up/megastore/config/SecurityConfig.java, src/main/java/com/_up/megastore/controllers/implementations/OrderController.java, src/main/java/com/_up/megastore/controllers/interfaces/IOrderController.java, src/main/java/com/_up/megastore/controllers/requests/CancelOrderRequest.java, src/main/java/com/_up/megastore/controllers/responses/OrderResponse.java, src/main/java/com/_up/megastore/data/enums/State.java, src/main/java/com/_up/megastore/data/model/Order.java, src/main/java/com/_up/megastore/security/filter/JWTAuthenticationFilter.java, src/main/java/com/_up/megastore/security/utils/Endpoints.java, src/main/java/com/_up/megastore/services/implementations/OrderService.java, src/main/java/com/_up/megastore/services/interfaces/IOrderService.java, src/main/java/com/_up/megastore/services/mappers/OrderMapper.java, src/test/java/com/_up/megastore/integrations/implementations/OrderControllerTest.java, src/test/java/com/_up/megastore/services/implementations/OrderServiceTest.java, src/test/resources/scripts/orders/cancel_order.sql
Se implementó la funcionalidad para que tanto usuarios logueados como administradores puedan cancelar pedidos siempre y cuando **no estén en entrega**. Además de ello, como en los casos anteriores, se envía un mail al cliente asociado indicándole que su pedido se canceló con éxito.
Al igual que en las otras MRs de cambios de estado, se agregaron los correspondientes tests unitarios y tests de integración. Con esto, tenemos **completados los casos de prueba de tests unitarios de cambios de estados**. Quedan como 55 casos de prueba más :smile:.
Resulta que todos los cambios de estado ejecutan las mismas instrucciones. En vez de repetir código como un npc, agregué una función genérica para cambiar el estado de una orden según el método que se llame. Por ejemplo, para finalizar una orden:
``` …
```
=> feat: cancel order

src/main/java/com/_up/megastore/controllers/requests/RecoverPasswordRequest.java, src/main/java/com/_up/megastore/data/model/User.java, src/main/java/com/_up/megastore/data/repositories/IUserRepository.java, src/main/java/com/_up/megastore/services/implementations/TokenService.java, src/main/java/com/_up/megastore/services/implementations/UserService.java, src/main/java/com/_up/megastore/services/interfaces/ITokenService.java, src/main/java/com/_up/megastore/utils/EmailBuilder.java, src/test/java/com/_up/megastore/unit/limit/ActivateUserTest.java, src/test/java/com/_up/megastore/unit/limit/UserTests.java, src/test/java/com/_up/megastore/unit/states/UserStateTest.java
Se implementó la funcionalidad para que expiren los tokens de recuperación de contraseña de la misma manera que en #60. Además de ello, se modificó la request para que la validación de la contraseña restaurada sea igual a la validación de la contraseña en el signup.
Se implementó el último caso de prueba faltante de los **tests unitarios de valor límite**. Con esto, tenemos 20/60 casos de prueba totales implementados.
=> feat: expire token password

src/main/java/com/_up/megastore/controllers/responses/ProductResponse.java, src/main/java/com/_up/megastore/services/mappers/ProductMapper.java
Ahora se retorna la ID de la variante del producto, en lugar de su nombre.
=> ref: return correct variant data

src/main/java/com/_up/megastore/controllers/implementations/CategoryController.java, src/main/java/com/_up/megastore/controllers/implementations/ProductController.java, src/main/java/com/_up/megastore/controllers/interfaces/ICategoryController.java, src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java, src/main/java/com/_up/megastore/controllers/responses/ProductResponse.java, src/main/java/com/_up/megastore/data/repositories/ICategoryRepository.java, src/main/java/com/_up/megastore/data/repositories/IProductRepository.java, src/main/java/com/_up/megastore/services/implementations/CategoryService.java, src/main/java/com/_up/megastore/services/implementations/ProductService.java, src/main/java/com/_up/megastore/services/interfaces/ICategoryService.java, src/main/java/com/_up/megastore/services/interfaces/IProductService.java, src/main/java/com/_up/megastore/services/mappers/ProductMapper.java
Ahora existe un endpoint para obtener los productos y las categorías eliminadas. 
Con respecto a los productos, cambié un par de cosas:
- La respuesta del ProductResponse, agregué atributos como _hasVariants_ y _variantOfName_, ya que son importantes en el frontend para mostrar información y para ofrecer una mejor experiencia de usuario a la hora de querer eliminar un producto: al tener el _hasVariants_ podemos habilitar/deshabilitar el botón de eliminar producto como más nos convenga.
- Opté por mostrar todos los productos, es decir, el super producto y sus variantes. Ya que como administrador en el panel necesito ver todos y no solo los super productos, creo que esto es lo más fácil y rápido que podemos hacer.
Ahí podemos ver cómo el botón está deshabilitado ya que el producto tiene …
=> feat: get deleted products and categories

src/main/java/com/_up/megastore/security/filter/JWTAuthenticationFilter.java, src/main/java/com/_up/megastore/security/utils/Endpoints.java, src/main/resources/package.sql
Se realizaron dos fixes de implementaciones previas:
1. En el procedimiento almacenado de get orders by state ocurría un null pointer cuando no había pedidos entre las fechas ingresadas. Esto ocurría porque, en MySql, cuando se realiza un SUM de una entidad que no se encuentra, en vez de devolver 0 se devuelve NULL. Esto se solucionó con la sentencia IFNULL que previene estos casos.
2. En la obtención de las entidades eliminadas, los usuarios normales podían acceder al endpoint. Esto se solucionó modificando los endpoints dentro de la clase Endpoints (estaban mal escritos) y añadiendo una condición extra en el método shouldNotFilter del JWT para indicar que los endpoints de entidades eliminadas SÍ se filtren.
=> fix: reports and security

src/main/java/com/_up/megastore/config/SecurityConfig.java, src/main/java/com/_up/megastore/controllers/implementations/UserController.java, src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java, src/main/java/com/_up/megastore/controllers/responses/AuthResponse.java, src/main/java/com/_up/megastore/exception/ExceptionControllerAdvice.java, src/main/java/com/_up/megastore/exception/ExceptionMessages.java, src/main/java/com/_up/megastore/services/implementations/AuthService.java, src/main/java/com/_up/megastore/services/implementations/UserService.java, src/main/java/com/_up/megastore/services/interfaces/IUserService.java
Ahora es posible visualizar las órdenes de un usuario a través de su username.
Inicialmente se había planteado hacerlo mediante el ID del usuario, pero, de manera más práctica, y aprovechando los métodos de seguridad como @PreAuthorize, se opta por utilizar el username, ya que el holder no expone el ID del usuario autenticado.
En cuanto a los permisos de lectura, se establecen de la siguiente manera:
- El usuario que realiza la solicitud debe ser el creador de las órdenes o tener rol de administrador.
=> feat: get orders by user
